config/routes.rb
Katalog::Application.routes.draw do
  
  get "advanced_search/home"
  get "advanced_search/range_release"
  get "advanced_search/title_search"

  get "welcome/index"
  get "artists/writers"
  get "artists/directors"
  get "artists/cast"
  get "artists/search"
  get "films/search"

  root 'welcome#index'

  resources :artists do
    resources :pictures
  end
  resources :films do
    resources :pictures
  end
  resources :countries
  resources :media
  resources :professions

  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  # include ActionView::Helpers::DateHelper
	attr_reader :profession_tokens

  before_save :name_normalize
  after_find do
    self.birthday = I18n.l self.birthday if self.birthday
    self.death = I18n.l self.death if self.death
  end
	
  has_and_belongs_to_many :professions
  has_many                :films, :through => :production_team
  has_many                :production_team, dependent: :nullify
  belongs_to              :country
  has_many :pictures, as: :imageable
  # accepts_nested_attributes_for :pictures

  mount_uploader :photo, PhotoUploader

  scope :directors, -> { joins(:professions).where(professions: {id: 2})}
  scope :writers,   -> { joins(:professions).where(professions: {id: [3, 6]})}
  scope :cast,      -> { joins(:professions).where(professions: {id: [1, 4]})}
  scope :random,    -> {order('random()')} #specific to postgresql

  paginates_per 10

  validates :name, uniqueness: { scope: :birthday, case_sensitive: false}


  def profession_tokens=(ids)
    self.profession_ids = ids.split(",")
  end

  def height_presenter
    if self.height.present?
      return "#{self.height.insert(1, ',')} m" if self.height.size == 3
      return "#{self.height.insert(0, '0,')} m" if self.height.size == 2
    end
  end
  
  def age
    diff = 0
    if self.birthday && !self.death
      # distance_of_time_in_words(self.birthday, Date.today)
      diff = Date.today - self.birthday
    end
    if self.birthday and self.death
      # distance_of_time_in_words(self.birthday, self.death)
      diff = self.death - self.birthday
    end
    years, rest = diff.abs.divmod(365.25)
    months = rest / 30 if rest > 0
    age = "#{years} ano#{"s" if years > 1}"
    if months and months > 1       
      age << " e #{months.to_i} mês" if months < 2
      age << " e #{months.to_i} meses" if months > 2
    end
    return age   
      
  end

  def self.search(search)
    if search
      where("i_unaccent(#{self.table_name}.name) LIKE i_unaccent(?)", "%#{search}%")
    else
      self.all
    end
  end

  protected
  def name_normalize
    re = /\s+[ixv]{,3}\z/i # for names ends with II, III and so on
    if self.name
      str = self.name.strip.squeeze(' ')
      str =~ re
      self.name = str.sub(re, $~.to_s.upcase)      
    end

    if self.real_name
      str = self.real_name.strip.squeeze(' ')
      str =~ re
      self.real_name = str.sub(re, $~.to_s.upcase)
    end
    
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  respond_to :html, :json
  include ActionView::Helpers::NumberHelper
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  

	def index
    # @artists = Artist.search(params[:search]).order('artists.name').paginate(page: params[:page], per_page: 2)
    @artists = Artist.search(params[:search]).order('artists.name').page(params[:page])

    respond_to do |format|
      format.html
      format.json {@artists.as_json(only: [:id, :name])}
      format.pdf {
        render pdf: "artists-list-report",
        encoding: 'utf-8',
        header: {center: "[ #{I18n.l Date.today, format: '%d.%m.%Y'} - #{number_with_delimiter(Artist.count)} artistas cadastrados. ]"},
        footer: {center: "[page] de [topage]"}
      }
    end
	end
  def search
    @artists = Artist.search(params[:q])
    # @artists = Artist.random.limit 3
  end
## Only to attend autocomplete plugin tokenInput
  def writers
    @artists = Artist.writers.uniq.search(params[:q])
    respond_with @artists.as_json(only: [:id, :name])
  end
  def directors
    @artists = Artist.directors.search(params[:q])
    respond_with @artists.as_json(only: [:id, :name])
  end
  def cast
    @artists = Artist.cast.search(params[:q])
   respond_with @artists.as_json(only: [:id, :name]) 
  end
## end actions to token input

  def new
    @artist = Artist.new
    # @picture = @artist.pictures.build      
  end

  def edit
    @imageable = @artist
    @pictures = @imageable.pictures
    @picture = Picture.new
  end

  def create
    # render inline: "<%= params[:action] %>"
    @artist = Artist.new(artist_params)
    respond_to do |format|
      if @artist.save
        # params[:pictures]['image'].each do |p|
        #   @pictures = @artist.pictures.create!(image: p, imageable_id: @artist.id, imageable_type: "Artist")
        # end
        format.html { redirect_to @artist, notice: 'Artista criado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @artist }
      else
        format.html { render action: 'new' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @artist.update(artist_params)
        # @artist.pictures.clear
        # params[:pictures]['image'].each do |p|
        #   @pictures = @artist.pictures.create!(image: p, imageable_id: @artist.id, imageable_type: "Artist")
        # end
        format.html { redirect_to @artist, notice: 'Artista atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @imageable = @artist
    @pictures = @imageable.pictures
    @picture = Picture.new
  end

  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])

  end

  
  # Never trust parameters from the scary internet, only allow the white list through.
  def artist_params
    params.require(:artist).permit(:name, :real_name, :profession_tokens,
      :birthday, :country_id, :photo, :height, :death, :remove_photo)
    # params.require(:film).permit(:artist_tokens)
  end

    
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<% content_for :title, navigation %>
<% if @artist.errors.any? %>
  <section class="col-sm-offset-3 col-sm-7 panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title text-center">Erros no formulário!</h3>
    </div>
    <div class="panel-body">
      <ul>
        <% @artist.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end -%>
      </ul>
    </div>
  </section>
<% end -%>
<%= form_for(@artist, html: {multpart: true, class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <%= f.label :name, class: "col-sm-3 control-label" %>
      <div class="col-sm-7">
        <%= f.text_field :name, class: "form-control input-sm fill validate[required]" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :real_name, class: "col-sm-3 control-label" %>
      <div class="col-sm-7">
        <%= f.text_field :real_name, class: "form-control input-sm fill" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :height, class: "col-sm-3 control-label" %>
      <div class="col-sm-3 input-group">
        <%= f.number_field :height, class: "form-control input-sm fill text-right validate[custom[integer],min[60],max[260]]" %><span class="input-group-addon">cm</span>
      </div>
      <%= f.label :country_id, "País", class: "col-sm-1 control-label" %>
      <div class="col-sm-3">
        <%#= f.text_field :country, class: "form-control fill", data: {countries: @countries}, placeholder: "Digite para buscar..." %>
        <%= f.text_field :country_id, class: "artist_country", data: {pre: Array.new(1, @artist.country.as_json(only: [:id, :name], methods: :url_16))} %>
      </div>
    </div>

    <div class="form-group">
      <label for="artist_birthday" class="col-sm-3 control-label">
        <span class="glyphicon glyphicon-star tip" data-toggle="tooltip"
        title="Nascimento"></span>
      </label>
      <div class="col-sm-3">
        <%= f.text_field :birthday, placeholder: 'DD/MM/AAAA', class: "form-control input-sm date fill text-center validate[custom[validDate]]"%>
        
      </div>      
      <label for="artist_death" class="col-sm-1 control-label">
        <span class="glyphicon glyphicon-remove tip"
        data-toggle="tooltip" title="Falecimento"></span>
      </label>
        <div class="col-sm-3">
          <%= f.text_field :death, placeholder: 'DD/MM/AAAA', class: "form-control input-sm date fill text-center validate[custom[validDate]]" %>
        </div>
    </div>

    <div class="form-group">
      <%= f.label :profession_tokens, "Atividades", class: "col-sm-3 control-label" %>
      <div class="col-sm-3">
        <%= f.text_field :profession_tokens, class: "form-control artist_professions", data: {professions: Profession.all.as_json(only: [:id, :name]), pre: @artist.professions.as_json(only: [:id, :name])} %>
      </div>
    </div>

    <div class="form-group artist-photo">
      <%= f.label :photo, class: "col-sm-3 control-label" %>

      <div class="col-sm-4 fileinput fileinput-new artist-photo" data-provides="fileinput">
        <div class="fileinput-preview thumbnail artist-photo" data-trigger="fileinput" style="width: 100px; height: 130px;">
          <%= image_tag @artist.photo_url(:thumb) %>
        </div>

        <div class="artist-photo">
          <% if @artist.photo? %>
            <label class="control-label artist-photo"><%= f.check_box :remove_photo, class: "artist-photo" %> Remover</label>
          <% end -%>
        </div>

        <div class="artist-photo">
          <span class="btn btn-xs btn-default btn-file">
            <span class="fileinput-new">Escolher foto</span>
            <span class="fileinput-exists">Trocar</span>
            <%= f.file_field :photo %>
          </span>
          <a href="#" class="btn btn-xs btn-default fileinput-exists" data-dismiss="fileinput">Remover</a>
        </div>
        
      </div>
    </div>

    <div class="form-group artist-submit">
      <div class="col-sm-offset-3 col-sm-7">
        <%= f.submit nil, data: {:disable_with => 'Enviando...'}, class: "btn btn-sm btn-default" %>
      </div>
    </div>
<% end %>

<% if params[:action] == 'edit' %>
  <hr>
  <div id="pictures">
    <%= render @artist.pictures %>
  </div>
  <% if @artist.pictures.size < 6 %>
    <%= render file: 'pictures/new' %>
  <% end -%>
<% end -%>

app/views/artists/edit.html.erb
<div class="col-sm-offset-3 col-sm-7 above_title"></div>
<div class="col-sm-offset-3 col-sm-7 title">
  <h5 class="text-center"><span class="glyphicon glyphicon-user"></span> Editar Artista</h5>
</div>


<%= render 'form' %>

<%#= link_to 'Show', @artist %> <!-- | -->
<%#= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<% content_for :title, navigation %>
<div class="col-sm-12 above_title"></div>
<div class="col-sm-12 title">
  <h5 class="text-center">Lista de Artistas</h5>
</div>

<div class="row film-search">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <%= form_tag artists_path, method: "get", :class => "form-horizontal" do %>
      <div class="input-group input-group-sm">
        
        <%= search_field_tag :search, params[:search], class: "form-control" %>
        <!-- <label for="" class="col-sm-2 control-label">Filtrar</label> -->
        <span class="input-group-btn">
          <%= submit_tag "Filtrar", :name => "nil", :class => "btn btn-default", data: {:disable_with => "Aguarde..."} %>
        </span>

      </div>
    <% end -%>
  </div>
  <div class="col-sm-4"></div>
</div>

<div class="row paginate">
  <div class="col-sm-4"></div>
  <div class="col-sm-4 text-center">
    <%#= will_paginate @artists, {previous_label: "&larr;", next_label: "&rarr;", inner_window: 1, outer_window: 2} %>
    <%= paginate @artists %>
    <!-- <p><%#= page_entries_info @artists %></p> -->
  </div>
  <div class="col-sm-4"></div>
</div>

<div class="col-sm-12">

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Nome de Batismo</th>
        <th>Nascimento</th>
        <th>País</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
  
    <tbody>
      <% @artists.each do |artist| %>
        <tr>
          <td><%= link_to artist.name, artist %></td>
          <td><%= artist.real_name %></td>
          <td><%= I18n.l artist.birthday if artist.birthday %></td>
          <td><%= artist.country.name if artist.country %></td>
          <td><%= link_to 'Atualizar', edit_artist_path(artist), class: "btn btn-info btn-xs" %></td>
          <td><%= link_to artist, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-danger btn-xs" do %>
            <i class="fa fa-trash-o fa-lg"></i> Excluir
            <% end -%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
    
  <p class="text-center">
    <%= link_to 'Novo Artista', new_artist_path, class: "btn btn-default btn-xs" %>
  </p>
</div>

  

app/views/artists/index.pdf.erb
<table>
  <tbody>
    <% Artist.all.order(:name).each do |a| %>
      <tr>
        <td><%= "#{a.name}" %></td>
      </tr>
    <% end -%>
  </tbody>
</table>

app/views/artists/new.html.erb
<div class="col-sm-offset-3 col-sm-7 above_title"></div>
<div class="col-sm-offset-3 col-sm-7 title">
  <h5 class="text-center"><span class="glyphicon glyphicon-user"></span> Novo Artista</h5>
</div>

<%= render 'form' %>

app/views/artists/show.html.erb
<% content_for :title, navigation %>
<div class="row">
  
  <section id="artist-images" class="col-sm-3">
    
    

    <%= link_to(@artist.photo_url(:normal), data: {lightbox: "photo"}, title:
    @artist.name) do %>
      <% image_tag @artist.photo_url(:medium).to_s, class: "img-thumbnail" %>
    <% end %>

    <p class='text-center artist'><strong>[ </strong>Produções: <span class="total"><%= @artist.films.uniq.size %></span> <strong> ]</strong></p>

    <div id='links' class="text-center">
      <%= link_to 'Editar', edit_artist_path(@artist), class: "btn btn-default btn-xs" %> |
      <%= link_to 'Voltar', artists_path, class: "btn btn-default btn-xs" %>
    </div>

    
    
  </section>

  <section id="artist-profile" class="col-sm-9">
    <h3 class="text-center"><%= @artist.name %> </h3>
       
    <p class="text-center art-real-name" >
      <small class="original-name tip" data-toggle="tooltip" data-placement="bottom" title="Nome de batismo">" <%= @artist.real_name %> "</small>&nbsp; <%= image_tag(@artist.country.flag.url(:_16), title: @artist.country.name, class: 'tip', data: {toggle: 'tooltip', placement: 'right'}) if @artist.country%>
    </p>
    <% if @artist.death %>
      <p class="text-center">
        <small><%= "(#{@artist.birthday.year} - #{@artist.death.year})" %></small>
    
      </p>      
    <% end %>
    
    <table id="artist-data" class="table table-borderless">
      <colgroup>
        <col width="130">
        <col>
      </colgroup>
      <tr>
        <td class="text-right"><strong>Nascimento:</strong></td>
        <td>
          <% if @artist.birthday %>
            <%= @artist.birthday.to_s(:br_date) %>&nbsp;
            <small><%= "(#{@artist.age})" %></small>
          <% end %>
        </td>
      </tr>
      <% if @artist.death %>
        <tr>
          <td class="text-right"><strong>Falecimento:</strong></td>
          <td><%= I18n.l @artist.death %></td>
        </tr>
      <% end -%>
      <tr>
        <td class="text-right"><strong>Estatura:</strong></td>
        <td><%= @artist.height_presenter %></td>
      </tr>      
      <tr>
        <td class="text-right"><strong>Atividades:</strong></td>
        <td><%= @artist.professions.map(&:name).join(", ") unless @artist.professions.empty? %></td>
      </tr>
      <tr>
        <td class="text-right"><strong>Produções:</strong></td>
        <td>
          <%= @artist.films.map {|e| normalize_title(e.brazilian_title)}.uniq.join(", ").truncate(90, separator: ' ', omission: '') unless @artist.films.empty? %>&nbsp;
          <em><small><%= link_to '...mais', '#artist-productions', data: {toggle: 'modal'} if @artist.films.map {|e| normalize_title(e.brazilian_title)}.uniq.join(", ").length > 90 %></small></em>
        </td>
      </tr>      
    </table>

    <% unless @artist.films.empty? %>
      <ul id="artist-films" class="bxslider">
        <% @artist.films.uniq.each do |f| %>
          <li>
            <%= link_to(image_tag(f.poster_url(:thumb), title: normalize_title(f.brazilian_title), class: "img-thumbnail"), f) %>
          </li>
        <% end %>
      </ul>
    <% end %>

  </section>

</div>
<hr>
<div id="pictures">
  <%= render @artist.pictures %>
</div>
<% if @artist.pictures.size < 6 %>
  <%= render file: 'pictures/new' %>
<% end -%>

<!-- bootstrap modal -->
<div class="modal fade" id="artist-productions" tabindex="-1" role="dialog" aria-labelledby="artistModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="artistModalLabel"><%= @artist.name %> <small>(produções)</small> </h4>
      </div>
      <div class="modal-body">
        <!-- <ul> -->
        <% @artist.films.order(:release).uniq.each do |f| %>
          <p><em><small><%= link_to "#{normalize_title(f.brazilian_title)} (#{f.release.year if f.release})", f %></small></em></p>
        <% end -%>
        <!-- </ul> -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>