config/routes.rb
Katalog::Application.routes.draw do
  
  get "advanced_search/home"
  get "advanced_search/range_release"
  get "advanced_search/title_search"

  get "welcome/index"
  get "artists/writers"
  get "artists/directors"
  get "artists/cast"
  get "artists/search"
  get "films/search"

  root 'welcome#index'

  resources :artists do
    resources :pictures
  end
  resources :films do
    resources :pictures
  end
  resources :countries
  resources :media
  resources :professions

  

end

app/models/film.rb
class Film < ActiveRecord::Base
  attr_reader      :poster_cache
  attr_reader      :cast_ids, :writer_ids, :director_ids
  attr_accessor    :cast_has_changed, :writers_has_changed, :directors_has_changed
  mount_uploader   :poster, PosterUploader #Gem carrierwave
  has_many         :production_team, dependent: :destroy
  has_many         :artists, :through => :production_team
  belongs_to       :country
  scope            :random, -> {order('random()')}
  has_many :pictures, as: :imageable
  paginates_per 10

  validates :title, uniqueness: { scope: :release, case_sensitive: false}

  after_initialize do
    self.release               = I18n.l self.release if self.release
    self.cast_has_changed      = false
    self.writers_has_changed   = false
    self.directors_has_changed = false
    

    if not self.artist_ids.empty? and self.cast.empty? and self.writers.empty? and self.directors.empty?
      self.cast_ids += self.artist_ids      
    end
  end

  before_save :set_production_team, on: [:create, :update], if: :production_team_has_changed?
  before_save :bd_title, on: [:create, :update]
  
  def genre_asjson
    self.genre.split('|').map { |e| {name: e} }.as_json if self.genre
  end


  def genre_format
    self.genre.gsub('|', ' | ') if self.genre
  end

  def cast
    self.production_team.map { |e| e.artist if e.cast? }.compact.sort_by {|a| a.name}
    # cast.map(&:name).join(", ") unless cast.empty?
  end

  def directors
    self.production_team.map { |e| e.artist if e.director? }.compact.sort_by {|a| a.name}
    # directors.map(&:name).join(", ") unless directors.empty?
  end

  def writers
    self.production_team.map { |e| e.artist if e.writer? }.compact.sort_by {|a| a.name}
    # writers.map(&:name).join(", ") unless writers.empty?
  end

  def production_team_has_changed?
    if self.cast_has_changed or self.writers_has_changed or self.directors_has_changed or self.new_record?
      return true
    else
      return false
    end
  end

  def cast_ids=(ids)
    unless self.new_record?
      @cast_ids = self.cast.map(&:id)
      unless @cast_ids.map { |e| e.to_s } == ids.split(",")
        self.cast_has_changed = true    
      end
    end   
    @cast_ids = ids.split(",")    
  end

  def director_ids=(ids)
    unless self.new_record?
      @director_ids = self.directors.map(&:id)
      unless @director_ids.map { |e| e.to_s } == ids.split(",")
        self.directors_has_changed = true
      end
    end    
    @director_ids = ids.split(",")
  end

  def writer_ids=(ids)
    unless self.new_record?
      @writer_ids = self.writers.map(&:id) 
      unless @writer_ids.map { |e| e.to_s } == ids.split(",")
        self.writers_has_changed = true    
      end
    end    
    @writer_ids = ids.split(",")
  end

  def self.search(col= 'brazilian_title', search)
    if search
      where("i_unaccent(films.#{col}) LIKE i_unaccent(?)", "%#{search}%")
    else
      self.all
    end
  end

  
  protected

  
  def set_production_team
    self.production_team.clear unless self.new_record?
    unless self.director_ids.empty?      
      self.director_ids.each do |d|
        self.production_team.build(artist_id: d.to_i, director: true)
      end
    end

    unless self.writer_ids.empty?
      self.writer_ids.each do |w|
        self.production_team.build(artist_id: w.to_i, writer: true)
      end
    end

    unless self.cast_ids.empty?
      self.cast_ids.each do |c|
        self.production_team.build(artist_id: c.to_i, cast: true)
      end
    end
  end

  def bd_title
    # re = /^[ao]s?n?\s+|^the\s+|^u[mn]a?s?\s+/i
    re = Regexp.new('^[ao]s?[[:blank:]]+|^the[[:blank:]]+|\Aan[[:blank:]]+|^u[mn]a?s?\s+', true)
    re_t = /\bi{2,3}\b|\bi[vx]\b|\b[vx]i{,3}\b/i # for titles with II, III and so on
    if self.brazilian_title
      self.brazilian_title = self.brazilian_title.strip.squeeze(' ')
      str = self.brazilian_title.sub(re, '')
      self.brazilian_title = str + ", #{Regexp.last_match.to_s.sub(/\s/, '')}" if
      Regexp.last_match
      str =~ re_t
      self.brazilian_title = self.brazilian_title.sub(re_t, $~.to_s.upcase)
    end
    if self.title
      self.title = self.title.strip.squeeze(' ')
      str = self.title.sub(re, '')
      self.title = str + ", #{$~.to_s.sub(/\s/, '')}" if $~
      str =~ re_t
      self.title = self.title.sub(re_t, $~.to_s.upcase)
    end
    
  end
  
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_action :set_film, only: [:show, :edit, :update, :destroy]
  # before_action :set_production_team, only: [:create, :update]
  before_action :genres_list, only: [:new, :edit, :update]
  
  # GET /films
  # GET /films.json
  def index
    # @films = Film.search(params[:search]).paginate(page: params[:page], per_page: 10).order('films.brazilian_title')
    @films = Film.search(params[:search]).order('films.brazilian_title').page(params[:page])

    respond_to do |format|
      format.html
      format.pdf {
        render pdf: "films-list-report",
        encoding: 'utf-8',
        header: {center: "[ #{I18n.l Date.today, format: '%d.%m.%Y'} - #{number_with_delimiter(Film.count)} filmes cadastrados. ]"},
        footer: {center: "[page] de [topage]"}
      }
    end
  end

  def search
    @films = Film.search(params[:q])
    # @films = Film.random.limit 3
  end
  # GET /films/1
  # GET /films/1.json
  def show
    @imageable = @film
    @pictures = @imageable.pictures
    @picture = Picture.new
  end

  # GET /films/new
  def new
    @film = Film.new    
  end

  # GET /films/1/edit
  def edit    
    @imageable = @film
    @pictures = @imageable.pictures
    @picture = Picture.new
  end

  # POST /films
  # POST /films.json
  def create
    # render text: params
    # render text: params[:film]
    @film = Film.new(film_params)
    # @film.cast_ids = params[:film][:cast_ids]         # force to call
    # @film.writer_ids = params[:film][:writer_ids]     # methods _ids
    # @film.director_ids = params[:film][:director_ids] # for new records
    # As tres atribuicoes acima sao para forcar a chamada aos respectivos meto-
    # dos que nao estavam sendo chamados quando da criacao de novos filmes.

    # render inline: "<%= @film.production_team.inspect %>"
    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Filme criado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @film }
      else
        format.html { render action: 'new' }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Filme atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:title, :brazilian_title, :release, :synopse, :poster, :genre,
        :cast_ids, :writer_ids, :director_ids, :poster_cache, :country_id, :length, :remove_poster)
    end


    def genres_list
      @genres = [
        {id: 1, name: "Ação"},
        {id: 2, name: "Aventura"},
        {id: 3, name: "Drama"},
        {id: 4, name: "Animação"},
        {id: 5, name: "Comédia"},
        {id: 6, name: "Ficção"},
        {id: 7, name: "Terror"},
        {id: 8, name: "Faroeste"},
        {id: 9, name: "Suspense"},
        {id: 10, name: "Policial"},
        {id: 11, name: "Romance"},
        {id: 12, name: "Guerra"},
        {id: 13, name: "Fantasia"},
        {id: 14, name: "Crime"},
        {id: 15, name: "Épico"},
        {id: 16, name: "Zumbi"}
      ].sort_by {|e| e[:name]}
    end
end

app/helpers/films_helper.rb
module FilmsHelper
  def normalize_title(str = 'none') #Film title (ex. "terminator, the" becomes "the terminator")
    re = /,\s+[ao]s?n?\z|,\s+the\z|,\s+u[mn]a?s?\z/i
    # str ||= "nenhum"
    str.sub!(re, '')
    return str unless $~
    str.prepend("#{$~.to_s.delete(",").lstrip} ")
  end
end

app/views/films/_form.html.erb
<% content_for :title, navigation %>

<% if @film.errors.any? %>
  <section class="col-sm-offset-3 col-sm-7 panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title text-center">Erros no formulário!</h3>
    </div>
    <div class="panel-body">
      <ul>
        <% @film.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end -%>
      </ul>
    </div>
  </section>
<% end -%>

<%= form_for(@film, html: {multipart: true, class: "form-horizontal", role: 'form'}) do |f| %>
  
  <div class="form-group">
    <%= f.label :brazilian_title, class: "col-sm-3 control-label" %>
    <div class="col-sm-7">
      <%= f.text_field :brazilian_title, class: "form-control input-sm fill validate[required]" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :title, class: "col-sm-3 control-label" %>
    <div class="col-sm-7">
      <%= f.text_field :title, class: "form-control input-sm fill" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :release, class: "col-sm-3 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :release, class: "form-control input-sm text-center fill validate[custom[validDate]]", placeholder: "dd/mm/aaaa" %>
    </div>
    <%= f.label :genre, class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :genre, class: "film_genre genero", data: {genres: @genres.as_json, pre: @film.genre_asjson} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :length, class: "col-sm-3 control-label" %>
    <div class="col-sm-3 input-group">
      <%= f.number_field :length, class: "form-control input-sm fill text-right"
      %><span class="input-group-addon">min</span>
    </div>
    <%= f.label :country_id, "País", class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :country_id, class: "film_country", data: 
      {pre: Array.new(1, @film.country.as_json(only: [:id, :name], methods: :url_16))} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :director_ids, "Direção", class: "col-sm-3 control-label" %>
    <div class="col-sm-7">
      <%= f.text_field :director_ids, class: "form-control directors", data:
      {pre: @film.directors.as_json(only: [:id, :name])} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :writer_ids, "Roteiro", class: "col-sm-3 control-label" %>
    <div class="col-sm-7">
      <%= f.text_field :writer_ids, class: "form-control writers", data: {pre:
        @film.writers.as_json(only: [:id, :name])} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cast_ids, "Elenco", class: "col-sm-3 control-label" %>
    <div class="col-sm-7">
      <%= f.text_field :cast_ids, class: "form-control cast", data: {pre: 
        @film.cast.as_json(only: [:id, :name])} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :synopse, class: "col-sm-3 control-label" %>
    <div class="col-sm-7">
      <%= f.text_area :synopse, class: "form-control" %>
    </div>
  </div>

  <div class="form-group film-poster">
    <%= f.label :poster, class: "col-sm-3 control-label" %>

    <div class="col-sm-4 film-poster fileinput fileinput-new" data-provides="fileinput">
      <div class="fileinput-preview thumbnail film-poster" data-trigger="fileinput" style="width: 100px; height: 130px;">
        <%= image_tag @film.poster_url(:thumb) %>
      </div>

      <div class="film-poster">
        <% if @film.poster? %>
          <label class="control-label film-poster"><%= f.check_box :remove_poster, class: "film-poster" %> Remover</label>
        <% end -%>
      </div>

      <div class="film-poster">
        <span class="btn btn-xs btn-default btn-file">
          <span class="fileinput-new">Escolher poster</span>
          <span class="fileinput-exists">Trocar</span>
          <%= f.file_field :poster %>
          <%= f.hidden_field :poster_cache %>
        </span>
        <a href="#" class="btn btn-xs btn-default fileinput-exists" data-dismiss="fileinput">Remover</a>
      </div>
      
    </div>
  </div>

  <div class="form-group film-submit">
    <div class="col-sm-offset-3 col-sm-7">
      <%= f.submit nil, data: {:disable_with => 'Enviando...'}, class: "btn btn-default btn-xs" %>
    </div>
  </div>
<% end %>

<% if params[:action] == 'edit' %>
  <hr>
  <div id="pictures">
    <%= render @film.pictures %>
  </div>
  <% if @film.pictures.size < 6 %>
    <%= render file: 'pictures/new' %>
  <% end -%>
<% end -%>

app/views/films/edit.html.erb
<div class="col-sm-offset-3 col-sm-7 above_title"></div>
<div class="col-sm-offset-3 col-sm-7 title">
  <h5 class="text-center"><span class="glyphicon glyphicon-film"></span> Editar Filme</h5>
</div>

<%= render 'form' %>

app/views/films/index.html.erb
<% content_for :title, navigation %>
<div class="col-sm-12 above_title"></div>
<div class="col-sm-12 title">
  <h5 class="text-center">Lista de Filmes</h5>
</div>

<div class="row film-search">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <%= form_tag films_path, method: "get", :class => "form-horizontal" do %>
      <div class="input-group input-group-sm">
        
        <%= search_field_tag :search, params[:search], class: "form-control" %>
        <!-- <label for="" class="col-sm-2 control-label">Filtrar</label> -->
        <span class="input-group-btn">
          <%= submit_tag "Filtrar", :name => "nil", :class => "btn btn-default", data: {:disable_with => "Aguarde..."} %>
        </span>

      </div>
    <% end -%>
  </div>
  <div class="col-sm-4"></div>
</div>

<div class="row paginate">
  <div class="col-sm-4"></div>
  <div class="col-sm-4 text-center">
    <%= paginate @films %>
  </div>
  <div class="col-sm-4"></div>
</div>

<div class="col-sm-12">

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Título Brasileiro</th>
        <th>Título Original</th>
        <th>Lançamento</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
  
    <tbody>
      <% @films.each do |film| %>
        <tr>
          <td><%= link_to film.brazilian_title, film %></td>
          <td><%= film.title %></td>
          <td><%= film.release.to_formatted_s(:br_date) if film.release %></td>
          <td><%= link_to 'Atualizar', edit_film_path(film), class: "btn btn-info btn-xs" %></td>
          <td><%= link_to "Excluir", film, method: :delete, data: {confirm: 'Tem certeza?' }, class: "btn btn-danger btn-xs"%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
    
  <p class="text-center">
    <%= link_to 'Novo Filme', new_film_path, class: "btn btn-default btn-xs" %>
  </p>
</div>

app/views/films/index.pdf.erb

<table>
  <tbody>
    <% Film.all.order(:brazilian_title).each do |film| %>
      <tr>
        <td><%= "#{film.brazilian_title} (#{film.release.year if film.release})" %></td>
      </tr>
    <% end -%>
  </tbody>
</table>
<!-- <ul class="list-group">
  <#% @films.each do |film| %>
    <li class="list-group-item">
      <span class="badge"><%#= film.release.year if film.release %></span>
      <%#= film.title %>
    </li>
  <#% end -%>
</ul> -->

app/views/films/new.html.erb
<div class="col-sm-offset-3 col-sm-7 above_title"></div>
<div class="col-sm-offset-3 col-sm-7 title">
  <h5 class="text-center"><span class="glyphicon glyphicon-film"></span> Novo Filme</h5>
</div>

<%= render 'form' %>

app/views/films/show.html.erb
<% content_for :title, navigation %>
<div class="row">
  
  <section id="film-img" class="col-sm-3 poster">
    <%= link_to(@film.poster_url(:normal), data: {lightbox: "poster"}, title: normalize_title(@film.brazilian_title)) do %>
      <% image_tag @film.poster_url(:medium), class: "img-thumbnail" %>
    <% end %>
    <p class='film-created tip' data-toggle='tooltip' data-placement='bottom' title="Data do cadastramento"><strong>[ </strong><%= I18n.l @film.created_at, format: '%d/%m/%Y, %H:%M' %> <strong> ]</strong></p>
    <div class="text-center">
      <%= link_to 'Editar', edit_film_path(@film), class: "btn btn-default btn-xs" %> |
      <%= link_to 'Voltar', films_path, class: "btn btn-default btn-xs" %>
    </div>
  </section>
  <section id="film-show" class="col-sm-9">
    <h3 class="text-center">
      <strong><%= normalize_title(@film.brazilian_title) if @film.brazilian_title.present?%></strong>
      <small><%= "(#{@film.release.year})" if @film.release%></small>
    </h3>
    
    <p class="text-center">
      <small class="original-name tip" data-toggle="tooltip" data-placement="bottom" title="Título original"> " <%= normalize_title(@film.title) if @film.title.present?%> "</small>&nbsp;
      <%= image_tag( @film.country.flag.url(:_16), title: @film.country.name, class: 'tip', data: {toggle: 'tooltip', placement: 'right'}) if @film.country %>
    </p>

    <table id="film-data" class="table table-borderless">
      <colgroup>
        <col width="130">
        <col>
      </colgroup>
      <tr>
        <td class="text-right"><strong>Lançamento:</strong></td>
        <td><%= l @film.release, format: :long_day if @film.release%></td>
      </tr>
      <tr>
        <td class="text-right"><strong>Gênero:</strong></td>
        <td><%= @film.genre_format %></td>
      </tr>
      <tr>
        <td class="text-right"><strong>Duração:</strong></td>
        <td><%= "#{@film.length} minutos" if @film.length.present? %></td>
      </tr>
      <tr>
        <td class="text-right"><strong>Direção:</strong></td>
        <td><%= @film.directors.map(&:name).join(", ") unless @film.directors.empty? %></td>
      </tr>
      <tr>
        <td class="text-right"><strong>Roteiro:</strong></td>
        <td><%= @film.writers.map(&:name).join(", ") unless @film.writers.empty? %></td>
      </tr>
      <tr>
        <td class="text-right"><strong>Sinopse:</strong></td>
        <td><%= @film.synopse %></td>
      </tr>
      <tr>
        <td class="text-right"><strong>Elenco:</strong></td>
        <td>
          <%= @film.cast.map(&:name).join(", ").truncate(90, separator: ' ', omission: '') unless @film.cast.empty? %>&nbsp;
          <em><small><%= link_to '...mais', '#film-cast', data: {toggle: 'modal'} if @film.cast.map(&:name).join(", ").length > 90 %></small></em>
        </td>
      </tr>
    </table>
        

    <% unless @film.cast.empty? %>
      <ul id="film_cast" class="bxslider">
        <% @film.cast.each do |a| %>
          <li>
            <%= link_to(image_tag(a.photo_url(:thumb), title: a.name, class: "img-thumbnail"), a) %>
          </li>
        <% end %>
      </ul>
    <% end %>
    
  </section>

</div>
<hr>
<div id="pictures">
  <%= render @film.pictures %>
</div>
<% if @film.pictures.size < 6 %>
  <%= render file: 'pictures/new' %>
<% end -%>
<!-- bootstrap modal -->
<div class="modal fade" id="film-cast" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><%= normalize_title(@film.brazilian_title) %> <small>(elenco)</small></h4>
      </div>
      <div class="modal-body">
        <!-- <ul> -->
        <% @film.cast.each do |a| %>
          <p><em><small><%= link_to a.name, a %></small></em></p>
        <% end -%>
        <!-- </ul> -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>