config/routes.rb
Katalog::Application.routes.draw do
  
  get "advanced_search/home"
  get "advanced_search/range_release"
  get "advanced_search/title_search"

  get "welcome/index"
  get "artists/writers"
  get "artists/directors"
  get "artists/cast"
  get "artists/search"
  get "films/search"

  root 'welcome#index'

  resources :artists do
    resources :pictures
  end
  resources :films do
    resources :pictures
  end
  resources :countries
  resources :media
  resources :professions

  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  mount_uploader :image, ImageUploader

  before_create :default_name

    def default_name
      self.info ||= File.basename(image.filename, '.*').titlecase if image
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # before_action :set_picture, only: [:show, :edit, :update, :destroy]
  respond_to :js, :html
  # before_action :load_model, only: [:create, :destroy]
  before_action :load_imageable
  # GET /pictures
  # GET /pictures.json
  def index
    # @pictures = Picture.all
    @pictures = @imageable.pictures
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    # @picture = @artist.pictures.new
    @picture = @imageable.pictures.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    # @picture = @artist.pictures.create(picture_params)    
    @picture = @imageable.pictures.create(picture_params)    
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @artist, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    # @picture = @artist.pictures.find(params[:id])
    @picture = @imageable.pictures.find(params[:id])
    # @picture = params[:id]
    @picture.destroy
    respond_to do |format|
      # format.html { redirect_to @artist, notice: "Imagem excluida com sucesso." }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      # @picture = Picture.find(params[:id])
    end

    def load_model
      # @model = Artist.find(params[:artist_id]) if params[:artist_id]
      # @model = Film.find(params[:film_id]) if params[:film_id]
      # case 
      # when params[:artist_id]
      #   @artist = Artist.find(params[:artist_id])
      # when params[:film_id]
      #   @film = Film.find(params[:film_id])  
      # end
    end

    def load_imageable
        resource, id = request.path.split('/')[1, 2]
        @imageable = resource.singularize.classify.constantize.find(id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:image, :info, :artist_id, :film_id)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_field :info %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/_picture.html.erb
<div class="artist-pictures">
  <%= div_for picture, class: "col-sm-2 images" do %>
    <%= link_to(picture.image_url(:normal), data: {lightbox: "imagem"}, title: picture.info) do %>
      <% image_tag picture.image_url(:thumb), title: picture.info, class: "center-block" %>
    <% end -%>
    <p class="text-center">
      <%= link_to([@imageable, picture], data: {confirm: 'Tem certeza?'}, method: :delete, class: 'btn btn-xs btn-labeled btn-danger img-remove', remote: true) do %>
      <span class="btn-label"><i class="glyphicon glyphicon-remove"></i></span> Remover
      <% end %>
    </p>
  <% end %>
</div>

app/views/pictures/create.js.erb
$('div.upload').empty();

<% if @picture.new_record? %>
  alert("Failed to upload painting: <%= j @picture.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#pictures").append("<%= j render(@picture) %>");
<% end %>

<% if @imageable.pictures.size >= 6 %>
  $('section#images').hide('slow');
<% end %>

app/views/pictures/destroy.js.erb
$("#picture_<%= @picture.id %>").remove();
<% if @imageable.pictures.empty? %>
  $('div#pictures').remove();
<% end %>

<% if @imageable.pictures.size < 6 %>
  $('section#images').show('slow');
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Info</th>
      <th>Artist</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.image %></td>
        <td><%= picture.info %></td>
        <td><%= picture.artist %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<section id="images" class="col-sm-12">
  <%#= form_for([@picture, @imageable.pictures.new], url: [@imageable, @imageable.pictures.new], html: {multpart: true, class: "form-horizontal", role: "form"}) do |f| %>
  <%= form_for [@imageable, @picture], html: {multpart: true, class: "form-horizontal", role: 'form'} do |f| %>
    <div class="row">
      <div class="col-sm-5"></div>

      <div class="center-block fileinput fileinput-new" data-provides="fileinput">
        <span class="btn btn-primary btn-file">
          <i class="glyphicon glyphicon-plus"></i>
          <span> Imagens</span>
          <%= f.file_field :image, multiple: true, name: "picture[image]" %>
        </span>
      </div>

      <div class="col-sm-5"></div>
        <%#= image_tag @artist.photo_url(:thumb), class: "img-thumbnail" if @artist.photo? %>
        <%#= f.file_field :photo, multiple: true %>
    </div>
  
  <% end %>

  <script id="template-upload" type="text/x-tmpl">
  <div class="upload">
    {%=o.name%}
    <div class="progress"><div class="progress-bar" style="width: 0%"><div></div>
  </div>
  </script>
</section>

app/views/pictures/oldnew.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @picture.image %>
</p>

<p>
  <strong>Info:</strong>
  <%= @picture.info %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @picture.artist %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>