config/routes.rb
Katalog::Application.routes.draw do
  
  get "advanced_search/home"
  get "advanced_search/range_release"
  get "advanced_search/title_search"

  get "welcome/index"
  get "artists/writers"
  get "artists/directors"
  get "artists/cast"
  get "artists/search"
  get "films/search"

  root 'welcome#index'

  resources :artists do
    resources :pictures
  end
  resources :films do
    resources :pictures
  end
  resources :countries
  resources :media
  resources :professions

  

end

app/views/layouts/_header.html.erb
<!-- Fixed navbar -->
<header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%#= link_to "KataLog", root_path, class: "navbar-brand" %>
      <%= link_to root_path, class: "navbar-brand", id: 'home' do %>
        <span class="glyphicon glyphicon-home"></span> KATALOG
      <% end -%>
      
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <%= content_tag :li, class: ("active" if params[:controller] == 'films') do %>
          <%= link_to films_path do %>
            <i class="fa fa-film fa-lg"></i> Filmes
          <% end %>
        <% end %>
        
        <%= content_tag :li, class: ("active" if params[:controller] == 'artists') do %>
          <%= link_to artists_path do %>
            <i class="fa fa-users fa-lg"></i> Artistas
          <% end %>
        <% end %>
        
        <li><a href="#contact"><i class="fa fa-video-camera fa-lg"></i> Blurays&DVDs</a></li>
        <li><a href="#contact"><i class="fa fa-book fa-lg"></i> Livros&HQs</a> </li>
        
      </ul>
      
      <%= form_tag(nil, class: "navbar-form navbar-left", role: 'search', id: 'f_search' ) do %>
        <!-- <input type="text" class="form-control" placeholder="&#xf002;" id="g_search"> -->
        <%= search_field_tag 'g_search', nil, class: "form-control", placeholder: "Buscar...",  autocomplete: 'off' %>
      
      <% end -%>

      <ul class="nav navbar-nav navbar-right">
        <%= content_tag :li, class: ("active" if params[:controller] == 'advanced_search') do %>
          <%= link_to advanced_search_home_path do %>
            <i class="fa fa-search fa-lg"></i> Buscas Avançadas
          <% end -%>
        <% end -%>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cadastro <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Novo Filme", new_film_path %></li>
            <li><%= link_to 'Novo Artista', new_artist_path %></li>
            <li><%= link_to 'Nova Profissão', new_profession_path %></li>
            <li><%= link_to 'Novo País', new_country_path %></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_main_nav.html.erb
<%= content_for :main_navigation do %>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <%= nav_tab "Filmes", films_path, current: current_tab %>
      <!-- <li class="active"><%#= link_to films_path do %>
        <span class="glyphicon glyphicon-film"></span> Filmes
      <%# end %>
      </li> -->
      <li><%= link_to artists_path do %>
        <span class="glyphicon glyphicon-user"></span> Artistas
      <% end %>
      </li>
      <li><a href="#contact">Contact</a></li>
      <!-- <li class="dropdown"> -->
        <%#= link_to films_path, data: {toggle: "dropdown"}, class: "dropdown-toggle" do %>
          <!-- Filmes<b class="caret"></b> -->
        <%# end %>
        <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown">Filmes<b class="caret"></b></a> -->
        <!-- <ul class="dropdown-menu"> -->
          <!-- <li><%#= link_to "Novo Filme", new_film_path %></li> -->
          <!-- <li><a href="#">Something else here</a></li> -->
          <!-- <li class="divider"></li> -->
          <!-- <li class="dropdown-header">Nav header</li> -->
          <!-- <li><a href="#">Separated link</a></li> -->
          <!-- <li><a href="#">One more separated link</a></li> -->
        <!-- </ul> -->
      <!-- </li> -->
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="../navbar/">Default</a></li>
      <li><a href="../navbar-static-top/">Static top</a></li>
      <li class="active"><a href="./">Fixed top</a></li>
    </ul>
  </div><!--/.nav-collapse -->
<% end %>

app/views/layouts/_sidebar.html.erb
<p class="text-center"><%= I18n.l Date.today, format: :long_day %></p>
<p id="total-films"><strong>Filmes cadastrados:</strong> <span class="total"><%= number_with_delimiter(Film.count) %></span></p>
<p>Últimas entradas:</p>
<% Film.last(3).each do |f| %>
  <p class='side-list'><strong>[</strong> <span class="d-create"><%= I18n.l f.created_at, format: '%d/%m/%Y, %H:%M' %></span> <strong>]</strong> - <%= normalize_title(f.brazilian_title) %></p>
  <hr>
<% end -%>
<p id='total-artists'><strong>Artistas cadastrados:</strong> <span class="total"><%= number_with_delimiter(Artist.count) %></span></p>

<p>Últimas entradas:</p>
<% Artist.last(3).each do |a| %>
  <p class='side-list'><strong>[</strong> <span class="d-create"><%= I18n.l a.created_at, format: '%d/%m/%Y, %H:%M' %></span> <strong>]</strong> - <%= a.name %></p>
  <hr>
<% end -%>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= favicon_link_tag  %>
    <title> <%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/header' %>
   
    <div class="container">


      <div class="row">

        <section id="sidebar" class="col-md-3 side">
          <%= render 'layouts/sidebar' %>
        </section>
        <section id="content" class="col-md-9 main" data-no-turbolink>
          <% if notice %>
          <section id="notifications" class="alert alert-success">
            <span class="glyphicon glyphicon-saved"></span>
            <%= notice %>
          </section>
          <% end %>

          <%= yield %>
        </section>
      </div>
    </div>
    
    <%= javascript_include_tag "application" %>

  </body>
</html>